const STOPS=[
  {
    id:"lax",
    day:"12 Aug 2026",
    title:"LAX to Barstow",
    hotel:"Home2 Suites Barstow",
    loc:"Los Angeles to Barstow, California",
    scene:"airport",
    brief:"Start the quest by leaving Los Angeles and heading into the Mojave Desert.",
    intel:["Route 66 became one of America's most famous road-trip routes.","The drive east from Los Angeles changes from city streets to desert highways."],
    hunt:["Photo of an airport or plane clue.","Photo of your first desert or mountain view.","Photo of a big American road sign."],
    activity:{title:"First road view",prompt:"Write three words that describe the first proper American road-trip view."},
    quiz:{question:"Which landscape should start appearing as you leave Los Angeles?",answer:"Desert",options:["Desert","Rainforest","Snowfields"]}
  },
  {
    id:"barstow",
    day:"12 Aug 2026",
    title:"Barstow Base Camp",
    hotel:"Home2 Suites Barstow",
    loc:"Barstow, California",
    scene:"desert",
    brief:"A desert road stop where railways, highways and Route 66 history meet.",
    intel:["Barstow sits in the Mojave Desert.","Old road towns like Barstow helped travellers cross long desert stretches."],
    hunt:["Photo with the word Barstow visible.","Photo of a cactus, yucca or dry desert plant.","Photo of a railway, truck stop or Route 66 clue."],
    activity:{title:"Base camp rating",prompt:"Rate Barstow as a road-trip base out of 10 and explain your score."},
    quiz:{question:"Barstow is best described as a...",answer:"Desert road stop",options:["Desert road stop","Beach resort","Ski village"]}
  },
  {
    id:"calico",
    day:"13 Aug 2026",
    title:"Calico Ghost Town",
    hotel:"Best Western Plus King's Inn, Kingman",
    loc:"Calico, California",
    scene:"ghost",
    brief:"A restored mining town level with boardwalks, old buildings and Wild West details.",
    intel:["Calico began as a silver mining town in 1881.","The restored town is now one of the most recognisable stops near old Route 66."],
    hunt:["Photo of the big Calico letters or entrance.","Photo of a wooden boardwalk or old shop front.","Photo of a mining, jail or sheriff clue."],
    activity:{title:"Ghost town scene",prompt:"Describe the building that looks most like it belongs in a Western film."},
    quiz:{question:"Calico is connected with which industry?",answer:"Silver mining",options:["Silver mining","Space rockets","Fishing"]}
  },
  {
    id:"bagdad",
    day:"13 Aug 2026",
    title:"Bagdad Cafe",
    hotel:"Best Western Plus King's Inn, Kingman",
    loc:"Newberry Springs, California",
    scene:"cafe",
    brief:"A classic roadside cafe level made famous by film and Route 66 travellers.",
    intel:["The film Bagdad Cafe made this stop internationally known.","Roadside cafes are a huge part of Route 66 culture."],
    hunt:["Photo of the Bagdad Cafe sign or building.","Photo of a Route 66 sticker, shield or souvenir.","Photo of one object that feels old-road or roadside."],
    activity:{title:"Cafe critic",prompt:"Write one sentence reviewing the stop like a travel writer."},
    quiz:{question:"Bagdad Cafe is famous partly because of a...",answer:"Film",options:["Film","Castle","Football stadium"]}
  },
  {
    id:"roys",
    day:"13 Aug 2026",
    title:"Roy's Motel and Cafe",
    hotel:"Best Western Plus King's Inn, Kingman",
    loc:"Amboy, California",
    scene:"neon",
    brief:"A neon-sign level in Amboy, one of the most photographed Route 66 spots in the Mojave.",
    intel:["Roy's began as a service station and motel stop.","Its tall neon sign is a classic Route 66 photo target."],
    hunt:["Photo of the Roy's sign.","Photo of the white motel cabins or cafe front.","Photo of a Route 66 shield on or near the road."],
    activity:{title:"Sign designer",prompt:"Describe what you would add to make the Roy's sign even more dramatic."},
    quiz:{question:"What is the famous thing to photograph at Roy's?",answer:"The sign",options:["The sign","A lighthouse","A ski lift"]}
  },
  {
    id:"needles",
    day:"13 Aug 2026",
    title:"Needles",
    hotel:"Best Western Plus King's Inn, Kingman",
    loc:"Needles, California",
    scene:"river",
    brief:"A hot desert town level near the Colorado River and the Arizona border.",
    intel:["Needles is near the Colorado River.","It is known as one of the hottest towns on the Route 66 corridor."],
    hunt:["Photo with the word Needles visible.","Photo of a river, bridge or railway clue.","Photo showing the dry desert landscape."],
    activity:{title:"Heat detective",prompt:"Write one thing that proves you are now properly in the desert."},
    quiz:{question:"Needles is near which river?",answer:"Colorado River",options:["Colorado River","River Thames","Nile"]}
  },
  {
    id:"oatman",
    day:"13 Aug 2026",
    title:"Oatman",
    hotel:"Best Western Plus King's Inn, Kingman",
    loc:"Oatman, Arizona",
    scene:"western",
    brief:"A mining-town level where old wooden storefronts and wandering burros make the street feel alive.",
    intel:["Oatman began as a mining town.","Wild burros are one of the town's best-known sights."],
    hunt:["Photo of a burro.","Photo of an old wooden shop front.","Photo of a mining-town or Route 66 sign."],
    activity:{title:"Burro report",prompt:"Write a short headline for the best burro moment you see."},
    quiz:{question:"Oatman is best known for animals called...",answer:"Burros",options:["Burros","Penguins","Kangaroos"]}
  },
  {
    id:"kingman",
    day:"13 Aug 2026",
    title:"Kingman Base Camp",
    hotel:"Best Western Plus King's Inn, Kingman",
    loc:"Kingman, Arizona",
    scene:"town",
    brief:"A major Arizona Route 66 level with old-road signs, railway history and diner-style stops.",
    intel:["Kingman is one of Arizona's best-known Route 66 towns.","Railway and road-trip history overlap here."],
    hunt:["Photo of a Kingman sign.","Photo of a train, track or railway clue.","Photo of a Route 66 mural, shield or diner-style sign."],
    activity:{title:"Stop ranking",prompt:"Rank today's stops so far and defend your number one."},
    quiz:{question:"Kingman is strongly linked with which road?",answer:"Route 66",options:["Route 66","Abbey Road","The M25"]}
  },
  {
    id:"peach",
    day:"14 Aug 2026",
    title:"Peach Springs",
    hotel:"The Grand Hotel at the Grand Canyon",
    loc:"Peach Springs, Arizona",
    scene:"desert",
    brief:"A dry Arizona level on the Hualapai Reservation, surrounded by open desert scenery.",
    intel:["Peach Springs is on the Hualapai Reservation.","It is one of the old Route 66 communities in Arizona."],
    hunt:["Photo of a Peach Springs or Hualapai clue.","Photo of a long straight road view.","Photo of red, orange or sandy-coloured rock."],
    activity:{title:"Desert colour chart",prompt:"List three colours you can see in the landscape."},
    quiz:{question:"Peach Springs is on old Route 66 in...",answer:"Arizona",options:["Arizona","Scotland","Florida"]}
  },
  {
    id:"seligman",
    day:"14 Aug 2026",
    title:"Seligman",
    hotel:"The Grand Hotel at the Grand Canyon",
    loc:"Seligman, Arizona",
    scene:"retro",
    brief:"A bright retro level full of old signs, classic cars and Route 66 revival energy.",
    intel:["Seligman helped keep Route 66 tourism alive.","The town is famous for colourful roadside Americana."],
    hunt:["Photo of a classic car.","Photo of a colourful Route 66 sign.","Photo of a shop display that feels deliberately retro."],
    activity:{title:"Postcard pick",prompt:"Describe the photo here that would make the best postcard."},
    quiz:{question:"Seligman is famous for which style?",answer:"Retro Route 66",options:["Retro Route 66","Arctic research","Submarine tours"]}
  },
  {
    id:"meteor",
    day:"14 Aug 2026",
    title:"Meteor Crater",
    hotel:"The Grand Hotel at the Grand Canyon",
    loc:"Winslow, Arizona",
    scene:"crater",
    brief:"A space-impact level where the landscape shows what one meteorite can do.",
    intel:["Meteor Crater was formed by a meteorite impact.","The crater is so large that viewpoints help show the scale."],
    hunt:["Photo of the crater rim.","Photo of a meteorite or space display.","Photo of a sign explaining the size or impact."],
    activity:{title:"Space headline",prompt:"Write a breaking-news headline as if the meteor had just landed."},
    quiz:{question:"Meteor Crater was formed by...",answer:"An impact",options:["An impact","Pirates","A volcano-shaped building"]}
  },
  {
    id:"bearizona",
    day:"14 Aug 2026",
    title:"Bearizona",
    hotel:"The Grand Hotel at the Grand Canyon",
    loc:"Williams, Arizona",
    scene:"wildlife",
    brief:"A wildlife level near Williams where the car becomes part of the adventure.",
    intel:["Bearizona is a wildlife park near Williams, Arizona.","Some areas are drive-through, so visitors view animals from the car."],
    hunt:["Photo of a bear or animal sign.","Photo of antlers, horns or another wildlife clue.","Photo of the funniest animal expression you see."],
    activity:{title:"Animal awards",prompt:"Give awards for funniest animal, calmest animal and most dramatic animal."},
    quiz:{question:"Bearizona is mainly about...",answer:"Wildlife",options:["Wildlife","Teddy bears only","Skyscrapers"]}
  },
  {
    id:"grand",
    day:"14-15 Aug 2026",
    title:"Grand Canyon",
    hotel:"The Grand Hotel at the Grand Canyon",
    loc:"Grand Canyon South Rim, Arizona",
    scene:"canyon",
    brief:"A canyon level with huge views, rock layers and the Colorado River far below.",
    intel:["The Colorado River helped carve the Grand Canyon.","The South Rim is the most visited part of the national park."],
    hunt:["Photo of the canyon view.","Photo showing at least three rock colours.","Photo of a safety or viewpoint sign."],
    activity:{title:"Canyon scale",prompt:"Write one sentence that explains how big the canyon feels in real life."},
    quiz:{question:"Which river helped carve the Grand Canyon?",answer:"Colorado River",options:["Colorado River","River Thames","Mississippi only"]}
  },
  {
    id:"desertview",
    day:"15 Aug 2026",
    title:"Desert View Watchtower",
    hotel:"The Grand Hotel at the Grand Canyon",
    loc:"Grand Canyon East Rim, Arizona",
    scene:"tower",
    brief:"A lookout-tower level at the eastern edge of the South Rim.",
    intel:["Desert View Watchtower was designed by Mary Colter.","The tower gives wide views across canyon and desert."],
    hunt:["Photo of the watchtower.","Photo of stonework or pattern details.","Photo of the widest view you can find."],
    activity:{title:"Lookout design",prompt:"Describe the feature that makes the tower feel like it belongs in the desert."},
    quiz:{question:"The watchtower gives visitors...",answer:"Wide views",options:["Wide views","Snowboarding lessons","An ocean harbour"]}
  },
  {
    id:"cameron",
    day:"15 Aug 2026",
    title:"Cameron Trading Post",
    hotel:"The Grand Hotel at the Grand Canyon",
    loc:"Cameron, Arizona",
    scene:"cafe",
    brief:"A trading-post level with food, gifts, local crafts and Southwest road-stop history.",
    intel:["Cameron Trading Post has served travellers for many decades.","Trading posts became important stops in the Southwest."],
    hunt:["Photo of the trading post sign.","Photo of pottery, weaving or craft patterns.","Photo of a postcard, magnet or souvenir."],
    activity:{title:"Souvenir judge",prompt:"Pick the best souvenir you see and explain why it wins."},
    quiz:{question:"A trading post is a place travellers might find...",answer:"Food and gifts",options:["Food and gifts","Rocket launches","Ice caves"]}
  },
  {
    id:"monument",
    day:"16 Aug 2026",
    title:"Monument Valley",
    hotel:"Bluff Dwellings Resort and Spa",
    loc:"Arizona and Utah border area",
    scene:"monument",
    brief:"A red-rock level with huge sandstone buttes and film-scene views.",
    intel:["Monument Valley is famous for sandstone buttes.","The landscape is on Navajo Nation land."],
    hunt:["Photo of a huge sandstone butte.","Photo of red rock layers.","Photo that looks like a film scene."],
    activity:{title:"Silhouette spotter",prompt:"Describe the outline of the most dramatic rock formation."},
    quiz:{question:"Monument Valley is famous for...",answer:"Sandstone buttes",options:["Sandstone buttes","Rainforest treehouses","Ice hotels"]}
  },
  {
    id:"forrest",
    day:"16 Aug 2026",
    title:"Forrest Gump Point",
    hotel:"Bluff Dwellings Resort and Spa",
    loc:"US-163 near Monument Valley, Utah",
    scene:"highway",
    brief:"A road-photo level looking towards Monument Valley from a famous film viewpoint.",
    intel:["This viewpoint is linked with the film Forrest Gump.","The road view points towards Monument Valley."],
    hunt:["Photo of the straight road view from a safe place.","Photo of Monument Valley in the distance.","Photo of a road sign or viewpoint clue."],
    activity:{title:"Movie caption",prompt:"Write a caption for the most dramatic road photo here."},
    quiz:{question:"What matters most at this photo stop?",answer:"Road safety",options:["Road safety","Standing in traffic","Blocking cars"]}
  },
  {
    id:"bluff",
    day:"16 Aug 2026",
    title:"Bluff Base Camp",
    hotel:"Bluff Dwellings Resort and Spa",
    loc:"Bluff, Utah",
    scene:"redrock",
    brief:"A red-rock base level in southeastern Utah after the Monument Valley run.",
    intel:["Bluff is a small town in southeastern Utah.","The area has dramatic red-rock scenery."],
    hunt:["Photo of a Bluff sign.","Photo of red rock near the hotel.","Photo of the best resort or sunset detail."],
    activity:{title:"Adventure hotel score",prompt:"Rate Bluff Dwellings out of 10 for adventure-hotel feeling."},
    quiz:{question:"Bluff is in which state?",answer:"Utah",options:["Utah","Nevada","New York"]}
  },
  {
    id:"horseshoe",
    day:"17 Aug 2026",
    title:"Horseshoe Bend",
    hotel:"Holiday Inn Express and Suites Page",
    loc:"Page, Arizona",
    scene:"riverbend",
    brief:"A viewpoint level where the Colorado River curves around a massive red-rock bend.",
    intel:["Horseshoe Bend is a huge curve in the Colorado River.","The viewpoint is near Page, Arizona."],
    hunt:["Photo showing the horseshoe shape.","Photo of the Colorado River below.","Photo of the safest viewpoint area or sign."],
    activity:{title:"River curve",prompt:"Describe the shape of the bend without using the word horseshoe."},
    quiz:{question:"Horseshoe Bend is shaped by the...",answer:"Colorado River",options:["Colorado River","Pacific Ocean","Grand Canal"]}
  },
  {
    id:"page",
    day:"17 Aug 2026",
    title:"Page Base Camp",
    hotel:"Holiday Inn Express and Suites Page",
    loc:"Page, Arizona",
    scene:"lake",
    brief:"A scenery-hub level close to Lake Powell, Horseshoe Bend and Antelope Canyon.",
    intel:["Page is close to Lake Powell and Antelope Canyon.","The city grew during the Glen Canyon Dam project era."],
    hunt:["Photo of a Page sign.","Photo of a Lake Powell, dam or canyon-tour clue.","Photo of a desert plant or red-rock view."],
    activity:{title:"Tomorrow planner",prompt:"Write the thing you are most excited to see at Antelope Canyon."},
    quiz:{question:"Which place is close to Page?",answer:"Lake Powell",options:["Lake Powell","The Eiffel Tower","Ben Nevis"]}
  },
  {
    id:"antelope",
    day:"18 Aug 2026",
    title:"Antelope Canyon",
    hotel:"Mandalay Bay, Las Vegas",
    loc:"Near Page, Arizona",
    scene:"slot",
    brief:"A slot-canyon level with curved sandstone walls and famous light patterns.",
    intel:["Antelope Canyon is a slot canyon.","Its curved walls were shaped by water and erosion."],
    hunt:["Photo of wave-like rock patterns.","Photo looking upward through the canyon.","Photo showing different orange sandstone tones."],
    activity:{title:"Photo angle",prompt:"Describe your best photo angle in one sentence."},
    quiz:{question:"What shaped Antelope Canyon over time?",answer:"Water and erosion",options:["Water and erosion","Paint rollers","Plastic moulds"]}
  },
  {
    id:"stgeorge",
    day:"18 Aug 2026",
    title:"St George Stop",
    hotel:"Mandalay Bay, Las Vegas",
    loc:"St George, Utah",
    scene:"redrock",
    brief:"A red-cliff road-stop level on the way towards Las Vegas.",
    intel:["St George is in southwestern Utah.","The city is surrounded by desert scenery and red cliffs."],
    hunt:["Photo of a St George sign.","Photo of red cliffs or desert scenery.","Photo of a road snack, rest stop or fuel-stop clue."],
    activity:{title:"Snack court",prompt:"Choose the best road-trip snack of the day and justify the ruling."},
    quiz:{question:"St George is useful today as a...",answer:"Road stop",options:["Road stop","Ferry terminal","Ski jump"]}
  },
  {
    id:"vegas",
    day:"18-20 Aug 2026",
    title:"Las Vegas Finale",
    hotel:"Mandalay Bay, Las Vegas",
    loc:"Las Vegas, Nevada",
    scene:"city",
    brief:"The final city level: bright lights, huge hotels and the finish line of the quest.",
    intel:["Las Vegas is famous for themed hotels and bright lights.","Mandalay Bay is at the southern end of the Strip."],
    hunt:["Photo of the Mandalay Bay sign.","Photo of three giant hotel names or signs.","Photo of the brightest or most over-the-top view."],
    activity:{title:"Final awards",prompt:"Give awards for brightest building, weirdest thing and best view."},
    quiz:{question:"Las Vegas is in which state?",answer:"Nevada",options:["Nevada","Arizona","California"]}
  }
];
