/* Route 66 Family Challenge — stop data with per-player pools and arcade games.
   huntPool: 7 items, each player gets 5 (picked by their name).
   quizPool: 4 questions, each player gets 3.
   game: the arcade mini-game for this stop. */
const STOPS=[
{id:'heathrow',day:'12 Aug 2026',unlock:'2026-01-01',emoji:'🛫',title:'London Heathrow',hotel:'Departure day',loc:'London, United Kingdom',
facts:['This is where the whole adventure begins!','Heathrow is one of the busiest airports in the entire world.','Our flight to Los Angeles takes about 11 hours and 15 minutes.'],
huntPool:['Find our flight on a departure board.','Spot a plane through the window.','Find our gate number.','Spot a shop selling sweets or snacks.','Find a sign pointing to departures.','Spot a pilot or cabin crew member.','Find a plane with a colourful tail design.'],
game:{type:'catch',title:'Baggage Blitz',prompt:'Catch the suitcases before they hit the floor — dodge the smelly socks!',good:['🧳','🎒','🧸'],bad:['🧦'],catcher:'🛒',target:12},
quizPool:[['The trip starts at London Heathrow.','true'],['Heathrow is a train station.','false'],['How long is the flight to Los Angeles?','About 11 hours',['About 11 hours','About 30 minutes','About 3 days']],['Which city are we flying to first?','Los Angeles',['Los Angeles','New York','Tokyo']]]},
{id:'lax',day:'12 Aug 2026',unlock:'2026-08-12',emoji:'🛬',title:'LAX Airport',hotel:'Home2 Suites Barstow',loc:'Los Angeles, California',
facts:['We have landed in America!','LAX stands for Los Angeles International Airport.','From here we collect the hire car and drive out to Barstow.'],
huntPool:['Find a sign that says Los Angeles or LAX.','Spot a palm tree.','Find the baggage claim area.','Spot an American flag.','Find the way to the car hire.','Spot a yellow taxi.','Find a sign in Spanish.'],
game:{type:'runner',title:'Runway Run',prompt:'Tap to jump the traffic cones and sprint off the runway!',player:'🚗',obstacle:'🚧',target:300},
quizPool:[['LAX is in Los Angeles.','true'],['LAX is in London.','false'],['What do we do after landing?','Pick up the hire car',['Pick up the hire car','Go skiing','Catch a boat']],['Which state is Los Angeles in?','California',['California','Texas','Florida']]]},
{id:'barstow',day:'12 Aug 2026',unlock:'2026-08-12',emoji:'🏨',title:'Barstow Base Camp',hotel:'Home2 Suites Barstow',loc:'Barstow, California',
facts:['Barstow sits right in the Mojave Desert.','It has been a road and railway stop for a very long time.','Travellers rested here before crossing the empty desert ahead.'],
huntPool:['Find the word Barstow on a sign or receipt.','Spot a cactus, yucca or desert plant.','Find a Route 66 shield shape.','Count three pickup trucks.','Find a mountain or rocky hill in the distance.','Spot a freight train or railway track.','Find the hotel ice machine.'],
game:{type:'memory',title:'Motel Match',prompt:'Flip the cards and match the pairs to check in!',icons:['🛏️','🔑','🧊','🚗','🌵','⭐']},
quizPool:[['Barstow is a good place to spot desert scenery.','true'],['The Mojave Desert is a rainforest.','false'],['Which word fits Barstow best?','Road stop',['Road stop','Ski village','Fishing island']],['What desert is Barstow in?','Mojave',['Mojave','Sahara','Gobi']]]},
{id:'needles',day:'13 Aug 2026',unlock:'2026-08-13',emoji:'🛣️',title:'Needles',hotel:'Best Western Plus King’s Inn, Kingman',loc:'Needles, California',
facts:['Needles is right next to the Colorado River.','It is one of the hottest towns along old Route 66.','It is named after the pointed mountain peaks nearby.'],
huntPool:['Find the word Needles.','Spot the Colorado River or a river sign.','Find a very dry-looking landscape.','Spot a train or railway.','Find an old Route 66-style motel sign.','Spot a temperature display.','Find a pointy mountain peak.'],
game:{type:'runner',title:'Desert Dash',prompt:'Tap to hop over the cacti — it is too hot to stop!',player:'🦎',obstacle:'🌵',target:300},
quizPool:[['Needles is near the Colorado River.','true'],['Needles is in Alaska.','false'],['What is Needles known for on road trips?','Heat and desert roads',['Heat and desert roads','Rainforests','Penguin beaches']],['What is Needles named after?','Pointy mountain peaks',['Pointy mountain peaks','Sewing needles','Pine trees']]]},
{id:'oatman',day:'13 Aug 2026',unlock:'2026-08-13',emoji:'🐴',title:'Oatman',hotel:'Best Western Plus King’s Inn, Kingman',loc:'Oatman, Arizona',
facts:['Oatman started as a gold mining town.','Wild burros (small donkeys) often wander down the main street.','The twisty mountain road into Oatman is part of the old Route 66.'],
huntPool:['Find a burro (donkey).','Spot an old wooden shop front.','Find a sign mentioning Route 66.','Look for something from the mining days.','Find the funniest souvenir in a shop window.','Spot a burro eating something.','Find a horseshoe anywhere.'],
game:{type:'whack',title:'Burro Bop',prompt:'Tap the cheeky burros as they pop up — don’t tap the rocks!',mole:'🐴',decoy:'🪨',target:12,time:30},
quizPool:[['Oatman is known for donkeys wandering around.','true'],['Oatman is a giant airport.','false'],['What was Oatman originally?','A mining town',['A mining town','A space station','A beach resort']],['What metal was mined at Oatman?','Gold',['Gold','Chocolate','Ice']]]},
{id:'kingman',day:'13 Aug 2026',unlock:'2026-08-13',emoji:'🏨',title:'Kingman Base Camp',hotel:'Best Western Plus King’s Inn, Kingman',loc:'Kingman, Arizona',
facts:['Kingman is one of Arizona’s main Route 66 towns.','It makes a good base for exploring old sections of the road.','Railway history and road-trip history meet here.'],
huntPool:['Find a Kingman sign.','Spot a train, track or railway.','Find a Route 66 mural or shield.','Find an old diner sign.','Pick the best-looking road-trip snack.','Spot a classic American pickup.','Find a postcard of Kingman.'],
game:{type:'memory',title:'Route 66 Match',prompt:'Match the road-trip pairs to park up for the night!',icons:['🛣️','🚙','⛽','🍔','🎸','🌇']},
quizPool:[['Kingman is in Arizona.','true'],['Kingman is underwater.','false'],['Which road is Kingman famous for?','Route 66',['Route 66','The M25','Abbey Road']],['What meets in Kingman?','Road and railway history',['Road and railway history','Two oceans','Three ski slopes']]]},
{id:'peach',day:'14 Aug 2026',unlock:'2026-08-14',emoji:'🌵',title:'Peach Springs',hotel:'The Grand Hotel at the Grand Canyon',loc:'Peach Springs, Arizona',
facts:['Peach Springs is on the Hualapai Reservation.','It is one of the old Route 66 communities in Arizona.','The land here is dry, open and very different from home.'],
huntPool:['Find a Peach Springs sign.','Spot a cactus or desert plant.','Find a long, straight road view.','Look for a Hualapai sign.','Find a red, orange or sandy-coloured rock.','Spot an animal or bird.','Find the emptiest view you can.'],
game:{type:'catch',title:'Cactus Catch',prompt:'Catch the water drops to keep the desert plants alive — dodge the tumbleweeds!',good:['💧'],bad:['🌾'],catcher:'🪣',target:12},
quizPool:[['Peach Springs is on Route 66 in Arizona.','true'],['Peach Springs is in Scotland.','false'],['What landscape should you expect?','Dry desert scenery',['Dry desert scenery','Tropical jungle','Frozen lake']],['Whose reservation is Peach Springs on?','Hualapai',['Hualapai','Vikings','Romans']]]},
{id:'seligman',day:'14 Aug 2026',unlock:'2026-08-14',emoji:'🚗',title:'Seligman',hotel:'The Grand Hotel at the Grand Canyon',loc:'Seligman, Arizona',
facts:['Seligman is one of the most famous Route 66 towns.','It is packed with old signs, classic cars and fun roadside displays.','It helped keep Route 66 popular after the new motorway opened.'],
huntPool:['Find a classic car.','Find a colourful Route 66 sign.','Spot a funny shop display.','Find something that looks very retro.','Take a photo that looks like a postcard.','Spot a mannequin or dummy figure.','Find an old petrol pump.'],
game:{type:'whack',title:'Sign Spotter',prompt:'Tap the Route 66 shields as fast as you can — ignore the stop signs!',mole:'🛡️',decoy:'🛑',target:12,time:30},
quizPool:[['Seligman is famous for Route 66.','true'],['Seligman is famous for submarine tours.','false'],['What should you see lots of here?','Retro road signs',['Retro road signs','Igloos','Volcano boats']],['What kind of cars is Seligman full of?','Classic cars',['Classic cars','Racing submarines','Snowmobiles']]]},
{id:'meteor',day:'14 Aug 2026',unlock:'2026-08-14',emoji:'☄️',title:'Meteor Crater',hotel:'The Grand Hotel at the Grand Canyon',loc:'Winslow, Arizona',
facts:['Meteor Crater is a huge hole made by a space rock hitting Earth.','It happened around fifty thousand years ago.','It is so big it is hard to fit the whole thing in one photo.'],
huntPool:['Find the crater rim.','Spot a display about meteorites.','Find the best viewpoint.','Look for a size comparison sign.','Find something explaining the impact.','Spot a real piece of meteorite.','Find an astronaut reference.'],
game:{type:'whack',title:'Meteor Smash',prompt:'Tap the meteors before they crash — don’t tap the satellites!',mole:'☄️',decoy:'🛰️',target:12,time:30},
quizPool:[['Meteor Crater was made by a space rock.','true'],['Meteor Crater was dug by pirates.','false'],['What is the main thing to look at?','A huge crater',['A huge crater','A football stadium','A coral reef']],['Roughly how old is the crater?','50,000 years',['50,000 years','50 years','5 billion years']]]},
{id:'bearizona',day:'14 Aug 2026',unlock:'2026-08-14',emoji:'🐻',title:'Bearizona',hotel:'The Grand Hotel at the Grand Canyon',loc:'Williams, Arizona',
facts:['Bearizona is a wildlife park near Williams, Arizona.','In some parts you stay in the car and the animals roam free.','The name is a fun mix of the words bear and Arizona.'],
huntPool:['Spot a bear.','Find an animal crossing sign.','Spot antlers or horns.','Find the funniest animal face.','Count how many times someone says “aww”.','Spot a wolf or coyote.','Find a baby animal.'],
game:{type:'memory',title:'Animal Match',prompt:'Match the animal pairs to open the safari gates!',icons:['🐻','🐺','🦬','🦅','🦊','🦌']},
quizPool:[['Bearizona is near Williams, Arizona.','true'],['Bearizona is a museum about teddy bears only.','false'],['What should you mainly look for?','Wildlife',['Wildlife','Skyscrapers','Trains only']],['In drive-through parts, where do you stay?','In the car',['In the car','On a bike','In a canoe']]]},
{id:'grand',day:'14-15 Aug 2026',unlock:'2026-08-14',emoji:'🏜️',title:'Grand Canyon',hotel:'The Grand Hotel at the Grand Canyon',loc:'Grand Canyon South Rim, Arizona',
facts:['The Grand Canyon was carved mostly by the Colorado River.','The South Rim is the most visited part of the national park.','The canyon shows layers of rock like a giant history book.'],
huntPool:['Find the Colorado River if you can see it.','Spot at least three different rock colours.','Find a warning sign near the edge.','Listen for a language that is not English.','Take a dramatic canyon photo.','Spot a squirrel or bird.','Find a park ranger.'],
game:{type:'runner',title:'Canyon Runner',prompt:'Tap to leap the rocks along the rim trail — stay on your feet!',player:'🥾',obstacle:'🪨',target:350},
quizPool:[['The Colorado River helped carve the Grand Canyon.','true'],['The Grand Canyon is a tiny ditch behind a shop.','false'],['What should you do near the edge?','Stay back safely',['Stay back safely','Mess around','Lean over the rail']],['Which rim are we visiting?','South Rim',['South Rim','Moon Rim','East Pole']]]},
{id:'cameron',day:'15 Aug 2026',unlock:'2026-08-15',emoji:'🛍️',title:'Cameron Trading Post',hotel:'The Grand Hotel at the Grand Canyon',loc:'Cameron, Arizona',
facts:['Cameron Trading Post has served travellers for over a hundred years.','Trading posts were important stops across the American Southwest.','It is a good place for food, gifts and local crafts.'],
huntPool:['Find the trading post sign.','Spot pottery or woven patterns.','Find one thing you would actually buy.','Find a postcard or fridge magnet.','Spot a bridge, river or canyon nearby.','Find turquoise-coloured jewellery.','Spot a woven rug.'],
game:{type:'catch',title:'Souvenir Scoop',prompt:'Catch the souvenirs falling off the shelf — mind the scorpions!',good:['🏺','🧿','🪶'],bad:['🦂'],catcher:'🧺',target:12},
quizPool:[['Cameron Trading Post is a real traveller stop in Arizona.','true'],['A trading post is where astronauts launch rockets.','false'],['What might you find here?','Gifts and food',['Gifts and food','Penguins','Underground trains']],['How long has it served travellers?','Over 100 years',['Over 100 years','Two weeks','A million years']]]},
{id:'monument',day:'16 Aug 2026',unlock:'2026-08-16',emoji:'🌄',title:'Monument Valley',hotel:'Bluff Dwellings Resort and Spa',loc:'Arizona / Utah border',
facts:['Monument Valley is famous for its huge red sandstone towers.','It has appeared in lots of cowboy films and adverts.','The land is part of the Navajo Nation.'],
huntPool:['Find a huge sandstone tower.','Spot a long, empty road view.','Find layers of red rock.','Take a photo that looks like a film scene.','Find a sign about the Navajo Nation.','Spot a horse.','Find the biggest rock tower of all.'],
game:{type:'timing',title:'Golden Hour Shot',prompt:'Tap when the marker hits the golden zone to take 3 perfect sunset photos!',hits:3},
quizPool:[['Monument Valley is famous for sandstone towers.','true'],['It is famous for rainforest treehouses.','false'],['What colour are the rocks mostly?','Red and orange',['Red and orange','Bright purple','Ice blue']],['Whose land is Monument Valley part of?','The Navajo Nation',['The Navajo Nation','Atlantis','The Vikings']]]},
{id:'forrest',day:'16 Aug 2026',unlock:'2026-08-16',emoji:'📸',title:'Forrest Gump Point',hotel:'Bluff Dwellings Resort and Spa',loc:'US-163 near Monument Valley, Utah',
facts:['This spot is famous from the film Forrest Gump.','The road points straight towards Monument Valley.','It is a photo stop, but staying safe near traffic matters most.'],
huntPool:['Find the long, straight road view.','Spot Monument Valley in the distance.','Find a safe spot to stand.','Find someone doing the classic pose.','Notice how far away the rocks still look.','Spot a mile marker post.','Count the cars that stop for photos.'],
game:{type:'runner',title:'Gump Run',prompt:'Run, tap, run! Jump the potholes on the longest run of the trip.',player:'🏃',obstacle:'🕳️',target:400},
quizPool:[['Forrest Gump Point is famous from a film.','true'],['You should stand in moving traffic for photos.','false'],['What matters most here?','Road safety',['Road safety','Getting likes','Blocking cars']],['What does the road point towards?','Monument Valley',['Monument Valley','The sea','London']]]},
{id:'bluff',day:'16 Aug 2026',unlock:'2026-08-16',emoji:'🏨',title:'Bluff Base Camp',hotel:'Bluff Dwellings Resort and Spa',loc:'Bluff, Utah',
facts:['Bluff is a small town in southeast Utah.','It is surrounded by dramatic red-rock scenery.','It makes a great overnight stop after Monument Valley.'],
huntPool:['Find a Bluff sign.','Spot red rock near the hotel.','Find the best pool or resort feature.','Choose the best sunset colour.','Look for a local history display.','Spot a lizard or desert creature.','Find the comfiest chair at the resort.'],
game:{type:'memory',title:'Red Rock Match',prompt:'Match the desert pairs to earn your room key!',icons:['🏜️','🦎','🌅','🛏️','🔥','⛺']},
quizPool:[['Bluff is in Utah.','true'],['Bluff is a London Underground station.','false'],['What scenery is common nearby?','Red rock',['Red rock','Arctic ice','City skyscrapers']],['When do we stop at Bluff?','After Monument Valley',['After Monument Valley','Before Heathrow','After Vegas']]]},
{id:'horseshoe',day:'17 Aug 2026',unlock:'2026-08-17',emoji:'🌅',title:'Horseshoe Bend',hotel:'Holiday Inn Express and Suites Page',loc:'Page, Arizona',
facts:['Horseshoe Bend is a huge horseshoe-shaped curve in the Colorado River.','The viewpoint is near the town of Page, Arizona.','The drop is enormous, so staying back from the edge is a must.'],
huntPool:['Find the horseshoe shape.','Spot the Colorado River far below.','Find the safest viewpoint area.','Notice the colours of water against rock.','Take a wide photo.','Spot a boat far below on the river.','Find the shadiest spot on the walk.'],
game:{type:'timing',title:'Perfect Shot',prompt:'Tap when the marker hits the golden zone — 3 perfect photos of the bend!',hits:3},
quizPool:[['Horseshoe Bend is a curve in the Colorado River.','true'],['It is a theme park rollercoaster.','false'],['What should you be careful of?','The cliff edge',['The cliff edge','The gift shop carpet','The moon']],['Which town is the viewpoint near?','Page',['Page','Paris','Plymouth']]]},
{id:'page',day:'17 Aug 2026',unlock:'2026-08-17',emoji:'🏨',title:'Page Base Camp',hotel:'Holiday Inn Express and Suites Page',loc:'Page, Arizona',
facts:['Page is close to Lake Powell, Horseshoe Bend and Antelope Canyon.','It was built when the nearby Glen Canyon Dam was made.','It is a handy base for visiting all the amazing nearby sights.'],
huntPool:['Find a Page sign.','Spot a Lake Powell or dam reference.','Find a canyon tour sign.','Choose the best dinner option nearby.','Find the most desert-looking plant.','Spot a boat or kayak on a trailer.','Find a picture of Antelope Canyon.'],
game:{type:'catch',title:'Lake Powell Catch',prompt:'Catch the fish jumping in Lake Powell — dodge the old boots!',good:['🐟','🐠'],bad:['🥾'],catcher:'🎣',target:12},
quizPool:[['Page is close to Antelope Canyon and Horseshoe Bend.','true'],['Page is in Wales.','false'],['Which lake is nearby?','Lake Powell',['Lake Powell','Loch Ness','Lake Como']],['Why was Page built?','For the Glen Canyon Dam',['For the Glen Canyon Dam','For a theme park','For a football club']]]},
{id:'antelope',day:'18 Aug 2026',unlock:'2026-08-18',emoji:'🧡',title:'Antelope Canyon',hotel:'Mandalay Bay, Las Vegas',loc:'Near Page, Arizona',
facts:['Antelope Canyon is a narrow slot canyon.','Its curvy walls were shaped slowly by water and wind.','Beams of light and orange sandstone make it amazing for photos.'],
huntPool:['Find wave-like patterns in the rock.','Spot a beam of light or bright patch.','Find the narrowest bit you walk through.','Look straight up and describe it.','Count at least three shades of orange.','Spot sand trickling down a wall.','Find a rock shape that looks like an animal.'],
game:{type:'timing',title:'Light Beam Hunter',prompt:'Tap exactly when the light beam glows gold — catch 3 beams!',hits:3},
quizPool:[['Antelope Canyon is a slot canyon.','true'],['It was built from orange plastic.','false'],['What shaped the canyon walls?','Water and wind',['Water and wind','Paint rollers','Giant spoons']],['What makes the canyon glow?','Beams of light',['Beams of light','Neon signs','Torches only']]]},
{id:'stgeorge',day:'18 Aug 2026',unlock:'2026-08-18',emoji:'⛽',title:'St George Stop',hotel:'Mandalay Bay, Las Vegas',loc:'St George, Utah',
facts:['St George is in southwest Utah.','It is surrounded by red cliffs and desert.','It is a useful stop on the way to Las Vegas.'],
huntPool:['Find a St George sign.','Spot red cliffs.','Find a petrol or rest stop sign.','Choose the best road snack.','Notice how the scenery changes towards Vegas.','Spot the number 15 on a motorway sign.','Find something ice cold.'],
game:{type:'runner',title:'Fuel Run',prompt:'Tap to jump the cones and make it to the petrol station!',player:'🚙',obstacle:'🚧',target:300},
quizPool:[['St George is in Utah.','true'],['St George is in the middle of the ocean.','false'],['What is it useful for today?','A road stop',['A road stop','A ski jump','A ferry terminal']],['Where are we heading after St George?','Las Vegas',['Las Vegas','London','The Grand Canyon']]]},
{id:'vegas',day:'18-20 Aug 2026',unlock:'2026-08-18',emoji:'🎰',title:'Las Vegas Finale',hotel:'Mandalay Bay, Las Vegas',loc:'Las Vegas, Nevada',
facts:['Las Vegas is famous for huge themed hotels and bright lights.','Mandalay Bay sits at the southern end of the famous Strip.','The Strip is actually in a place called Paradise, Nevada.'],
huntPool:['Find the Mandalay Bay sign.','Spot three giant hotel names.','Find the brightest sign you can.','See something completely over-the-top.','Choose the best view of the Strip.','Spot a fountain show.','Find a building shaped like something else.'],
game:{type:'reels',title:'Lucky Lights',prompt:'Tap each reel to stop it — line up 2 or more matching lights to win!',icons:['⭐','🎲','💡','🍒','🔔']},
quizPool:[['Las Vegas is in Nevada.','true'],['Mandalay Bay is a tiny countryside cottage.','false'],['What is Las Vegas famous for?','Lights and big hotels',['Lights and big hotels','Igloos','Roman aqueducts']],['Where on the Strip is Mandalay Bay?','The southern end',['The southern end','The north pole','Under the lake']]]}
];
